#!/usr/bin/env bash
# Install nginx web server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me google.com permanent;' /etc/nginx/sites-available/default
service nginx restart
