#!/usr/bin/env bash
#instal proxy

sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*
echo -e "frontend haproxynode\n\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tmode http\n\tdefault_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "backend web-backend\n\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 898-web-01 34.74.131.201:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 898-web-02 3.92.147.2:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
