#!/usr/bin/env bash
# Script that displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number in a list format

count=1
for count in {1..100};
do
	if ((count % 5 == 0 && count % 3 == 0))
	then
		echo "FizzBuzz"
	elif ((count % 5 == 0))
	then
		echo "Buzz"
	elif ((count % 3 == 0))
	then
		echo "Fizz"
	else
		echo $count
	fi
done
