#!/usr/bin/env bash
# displays time
hour=0
minute=1
while [ "$hour" -lt 13 ];
do
	((minute = 1))
	echo "Hour: $hour"
	while [ "$minute" -lt 60 ];
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
