#!/usr/bin/env bash
# Configures the container to fit: nginx must be running as nginx user, nginx must be listening on all active IPs on port 8080
sudo service apache2 stop
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
su - nginx -c "sed -ie 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart"
